# Generated by Django 2.1 on 2018-10-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_attendconcert'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendconcert',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
