# Generated by Django 2.1 on 2018-10-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20181022_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='end_time',
        ),
        migrations.AddField(
            model_name='concert',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='concert_images'),
        ),
    ]
